image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - apk add --update nodejs npm python3 make g++
  - npm install -g @devcontainers/cli

build:
  stage: build
  tags:
    - docker
  env:
    - DOCKER_CLI_EXPERIMENTAL: enabled

  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker buildx create --use --name new-builder
    - devcontainer build --workspace-folder . --image-name ${CI_REGISTRY_IMAGE}:latest --cache-from ${CI_REGISTRY_IMAGE}:latest --platform linux/amd64
    - devcontainer build --workspace-folder . --image-name ${CI_REGISTRY_IMAGE}:latest --cache-from ${CI_REGISTRY_IMAGE}:latest --platform linux/arm64
    - docker push ${CI_REGISTRY_IMAGE}:latest
  rules:
  - changes:
    - .devcontainer/**
