# This is only used for developing the zsh-in-docker script, but can be used as an example.

FROM debian:bookworm

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ARG ASDF_VERSION=v0.13.1

LABEL org.opencontainers.image.authors="Michael Bianco <mike@mikebian.co>" \
    org.opencontainers.image.source=https://gitlab.personal.bryanph.com:8080:devcontainer\
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.title="ASDF Devcontainer Image" \
    org.opencontainers.image.description="A Docker image for use with VS Code's Remote Containers extension or GitHub codespaces."

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo git wget tar gpg build-essential \
    libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev curl \
    libncursesw5-dev xz-utils tk-dev libxml2-dev \
    libxmlsec1-dev libffi-dev liblzma-dev pinentry-tty nano\
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

USER $USERNAME

# Install ASDF
RUN git clone https://github.com/asdf-vm/asdf.git /home/$USERNAME/.asdf --branch $ASDF_VERSION

# RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.1/zsh-in-docker.sh)" -- \
COPY zsh-in-docker.sh /tmp
RUN  /tmp/zsh-in-docker.sh \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p asdf \
    -p direnv \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -p https://github.com/zsh-users/zsh-history-substring-search \
    -p https://github.com/zsh-users/zsh-syntax-highlighting \
    -p 'history-substring-search' \
    -a 'bindkey "\$terminfo[kcuu1]" history-substring-search-up' \
    -a 'bindkey "\$terminfo[kcud1]" history-substring-search-down'

COPY asdf-post-create.sh /home/$USERNAME/asdf-post-create.sh

COPY entrypoint.sh /home/$USERNAME/entrypoint.sh

RUN echo "\n. $HOME/.asdf/asdf.sh\n" | tee -a ~/.zshrc ~/.bashrc ~/.profile

ENTRYPOINT [ "/home/vscode/entrypoint.sh" ]
CMD ["-l"]