version: '3.8'
services:
  devcontainer:
    hostname: devcontainer
    image: gitlab.personal.bryanph.com:5050/bryanph/devcontainer:latest
    build:
      context: .
      dockerfile: ./Containerfile
    volumes:
      - ..:/workspaces/${PROJECT_NAME}:cached
    command: -c sleep infinity